### PR TITLE
Update entity for newer config

### PR DESCRIPTION
**Pull request by tijsverkoyen**
This PR added an Update Entity that will reflect if Home Assistant should be restarted

When a new config is uploaded to the Niko Home Control 2 Connected Controller the integration does not work properly. A restart of Home Assistant resolves the problem.

The root cause why it is not functioning anymore is not solved. Therefor a lot of research need to happen. I suspect the issue is that ID's of the devices are changing, or the gateway connection that is passed to the device is not the same anymore, ...

But at least there is now an Update entity that shows if Home Assistant should be restarted.

When a new version is available it will show:
update-available

If you click on the Update entity it will show more details, which will show:
* Installed version: the first time the integration was loaded, this should be about the same time when Home Assistant was started.
* Latest version: the last time the integration has received the device list, which only happens after a reconnect.
details

If everything is up to date it will look like:
up-to-date

## Fixes
This should be a solution for #15

### CODE REVIEW

**Comment by blatruwe** [comment]
seems to work as described:

after installation:
image

when updating the NHC:

image


after HASS restart:
image

**Comment by joleys** [comment]
I confirm the Update entity is working after a new upload from the NHC software.

On the other hand: after an upgrade (!) of the controller firmware, this is not working as expected.  Since this kind of upgrade is rather scarcely, this can be disregarded for now.

For info: log shows a lot of similar errors after a new device list is published by the controller.  Related to 2.17?
`2023-04-08 12:10:14.766 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.coco] Skip device (11d6fd6e-d6b7-4a91-b644-12f160b59b4c) as it has no Properties`
`2023-04-08 12:10:14.767 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.coco] Skip device (3e59f2fe-962d-4917-8357-4e5905d1c6a7) as it has no Properties`

**Review by joleys — APPROVED** [review]
Working for programming updates from the NHC software.

**Comment by tijsverkoyen** [comment]
@joleys I will create a release later this week when I fixed https://github.com/joleys/niko-home-control-II/issues/68

**Comment by joleys** [comment]
@tijsverkoyen Perfect!

**Pull request merged**
